furnitures = {
{
		name = "Single Sofa&Chair",
	{name = "Armless Chair", model = 1663, price = 200, offset = 0.5, isRenderable = true},
	{name = "Leather Chair", model = 1671, price = 250, offset = 0.5, isRenderable = true},
	{name = "Single Leather Sofa", model = 1704, price = 360, offset = 0, isRenderable = true},
	{name = "Single Leather Sofa", model = 1705, price = 330, offset = 0, isRenderable = true},
	{name = "Single Leather Sofa", model = 1708, price = 220, offset = 0, isRenderable = true},
	{name = "Armchair", model = 1711, price = 220, offset = 0, isRenderable = true},
	{name = "Leather Chair", model = 1714, price = 360, offset = 0},
	{name = "Skeleton Chair", model = 1721, price = 360, offset = 0, isRenderable = true},
	},
{
		name = "Table Chair",
	{name = "table with 4 chairs", model = 1594, price = 300, offset = 0.5, isRenderable = true},
	{name = "Little table", model = 1516, price = 100, offset = 0},
	{name = "glass table #1", model = 1817, price = 400, offset = 0, isRenderable = true},
	{name = "glass table #2", model = 1822, price = 200, offset = 0, isRenderable = true},
	{name = "TV table", model = 2311, price = 60, offset = 0, isRenderable = true},
	{name = "TV table", model = 2313, price = 60, offset = 0, isRenderable = true},
	{name = "TV table", model = 2314, price = 300, offset = 0, isRenderable = true},
	{name = "fast food table", model = 2644, price = 200, offset = 0.5, isRenderable = true},
	{name = "fast food table", model = 2764, price = 200, offset = 0.5, isRenderable = true},
	{name = "table with 2 chairs", model = 2802, price = 150, offset = 0.5, isRenderable = true},
	{name = "Table", model = 14869, price = 90, offset = 1},
	{name = "Desk with Computer 1", model = 1998, price = 90, offset = 1,isRenderable = true},
	{name = "Desk with Computer 2", model = 1999, price = 90, offset = 1,isRenderable = true},
	},
{
		name = "Multimedia",
	{name = "Small tv", model = 1747, price = 350, offset = 0.5, isRenderable = true},
	{name = "scuba tv", model = 1518, price = 250, offset = 1},
	{name = "Small tv", model = 1748, price = 350, offset = 0.5, isRenderable = true},
	{name = "Orta boy tv", model = 1749, price = 500, offset = 0.5, isRenderable = true},
	{name = "Orta boy tv", model = 1750, price = 500, offset = 1, isRenderable = true},
	{name = "Orta boy tv", model = 1751, price = 500, offset = 0.5, isRenderable = true},
	{name = "Orta boy tv", model = 1752, price = 500, offset = 1, isRenderable = true},
	{name = "Orta boy tv", model = 1781, price = 500, offset = 0.5, isRenderable = true},
	{name = "LED tv", model = 1786, price = 2500, offset = 0.5, isRenderable = true,isModding=true},
	{name = "Plazma TV", model = 1792, price = 800, offset = 0.5, isRenderable = true},
	{name = "tv with shelves", model = 2091, price = 12000, offset = 0},
	{name = "tv with shelves", model = 2093, price = 6000, offset = 0},
	{name = "Hi-fi", model = 2100, price = 150, offset = 0, isRenderable = true,isModding=true},
	{name = "Computer", model = 2190, price = 750, offset = 0, isRenderable = true,isModding=true},
	},
{
		name = "sofas",
	{name = "Leather Sofa", model = 2290, price = 500, offset = -0.2, isRenderable = true},
	{name = "Couch", model = 1766, price = 350, offset = 0, isRenderable = true},
	{name = "Couch", model = 1764, price = 400, offset = 0, isRenderable = true},
	{name = "Couch", model = 1763, price = 600, offset = 0, isRenderable = true},
	{name = "Couch", model = 1761, price = 600, offset = 0, isRenderable = true},
	{name = "Couch", model = 1760, price = 600, offset = 0, isRenderable = true},
	{name = "Couch", model = 1757, price = 600, offset = 0, isRenderable = true},
	{name = "Couch", model = 1756, price = 600, offset = 0, isRenderable = true},
	{name = "Couch", model = 1753, price = 600, offset = 0, isRenderable = true},
	{name = "Modern Couch", model = 1713, price = 250, offset = 0, isRenderable = true},
	{name = "Short Couch", model = 1712, price = 500, offset = 0, isRenderable = true},
	{name = "LONG Couch", model = 1710, price = 5000, offset = 0, isRenderable = true},
	{name = "Couch", model = 1709, price = 200, offset = 0, isRenderable = true},
	{name = "Couch", model = 1707, price = 200, offset = 0, isRenderable = true},
	{name = "Couch", model = 1706, price = 200, offset = 0, isRenderable = true},
	{name = "Couch", model = 1703, price = 200, offset = 0, isRenderable = true},
	{name = "Couch", model = 1702, price = 200, offset = 0, isRenderable = true},
	},
{
		name = "Lambs",
	{name = "Work Lamp", model = 2196, price = 50, offset = 0, isRenderable = true},
	},	
{
		name = "Bathroom Furniture",
	{name = "Dishwasher", model = 2340, price = 950, offset = 0, isRenderable = true},
	{name = "Washing machine", model = 1208, price = 550, offset = 0},
	{name = "Dryer #1", model = 2337, price = 750, offset = 0, isRenderable = true},
	{name = "Dryer #2", model = 2339, price = 950, offset = 0, isRenderable = true},
		
	},	
{
		name = "cabinets",
	{name = "Bookcase", model = 1742, price = 500, offset = 0, isRenderable = true},
	{name = "Single Shelf", model = 1744, price = 50, offset = 0, isRenderable = true},
	{name = "Multiple Shelves 1", model = 2462, price = 100, offset = 0, isRenderable = true},
	{name = "Multiple Shelves 2", model = 2463, price = 200, offset = 0},
	{name = "Multiple Shelves 3", model = 2475, price = 150, offset = 0},
	{name = "Table Shelf", model = 2482, price = 150, offset = 0},--silah raf sistemi gelcek buna
	{name = "Table Shelf", model = 2502, price = 50, offset = 0},
	{name = "Shelf", model = 2509, price = 50, offset = 0},
	{name = "Bookcase Shelf", model = 2608, price = 150, offset = 0},
	{name = "Dolap", model = 2708, price = 250, offset = 0},
	{name = "Cabinet with Bookcase and Drawers", model = 2164, price = 250, offset = 0},
	{name = "Cabinet with Bookcase and Drawers 2", model = 2161, price = 250, offset = 0},
	
	},	
{
		name = "Beds",
	{name = "Simple Bed", model = 1701, price = 350, offset = 0, isRenderable = true},
	{name = "Double bed", model = 1700, price = 350, offset = 0},
	{name = "Simple Bed", model = 1745, price = 350, offset = 0, isRenderable = true},
	{name = "Bunk", model = 1770, price = 150, offset = 0.5, isRenderable = true},
	{name = "Bed Without Base", model = 1793, price = 50, offset = 0, isRenderable = true},
	{name = "Double bed", model = 1794, price = 560, offset = 0, isRenderable = true},
	{name = "Bed", model = 1795, price = 460, offset = 0, isRenderable = true},
	{name = "Bed", model = 1796, price = 230, offset = 0, isRenderable = true},
	{name = "Bed", model = 1797, price = 50, offset = 0, offset = 0, isRenderable = true},
	{name = "Bed", model = 1798, price = 460, offset = 0, isRenderable = true},
	{name = "Bed", model = 1799, price = 460, offset = 0, isRenderable = true},
	{name = "Bunk", model = 1800, price = 150, offset = 0, isRenderable = true},
	{name = "Bunk", model = 1801, price = 150, offset = 0, isRenderable = true},
	{name = "Bed", model = 1802, price = 60, offset = 0, isRenderable = true},
	{name = "Supported Bed", model = 1803, price = 668, offset = 0, isRenderable = true},
	{name = "Covered Bed", model = 14880, price = 10, offset = 0},
	{name = "Bunk", model = 1812, price = 150, offset = 0, isRenderable = true},
	{name = "Bed", model = 2090, price = 500, offset = 0, isRenderable = true},
	{name = "Komidinli Bed", model = 2298, price = 500, offset = 0, isRenderable = true}
	},	
{
		name = "carpets",
	{name = "Orange Rug", model = 2847, price = 50, offset = 0},
	{name = "Green Rug", model = 2817, price = 50, offset = 0},
	{name = "Red Rug", model = 2818, price = 50, offset = 0},
	{name = "Oval Rug", model = 2841, price = 50, offset = 0},
	{name = "Red carpet", model = 2842, price = 50, offset = 0},
	},
{
		name = "Property Accessories",
	{name = "Potted Plant 1", model = 630, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 2", model = 631, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 3", model = 632, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 4", model = 633, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 5", model = 638, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 6", model = 646, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 7", model = 948, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 8", model = 949, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 9", model = 950, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 10", model = 1235, price = 75, offset = 0, isRenderable = true},
	{name = "Potted Plant 11", model = 1361, price = 75, offset = 0, isRenderable = true},
	{name = "Frame 1", model = 1583, price = 125, offset = 0, isRenderable = true},
	{name = "Frame 2", model = 1584, price = 125, offset = 0, isRenderable = true},
	{name = "Frame 3", model = 1585, price = 125, offset = 0, isRenderable = true},
	{name = "Automat", model = 1776, price = 225, offset = 0, isRenderable = true},
	{name = "Mop", model = 1778, price = 25, offset = 0, isRenderable = true},
	{name = "Sound system", model = 2229, price = 125, offset = 0, isRenderable = true},
	
	},
{
		name = "Kitchen ",
	{name = "Red Cabinet Set Piece", model = 2127, price = 375, offset = 0, isRenderable = true},
	{name = "Red Cabinet Set Piece", model = 2128, price = 375, offset = 0, isRenderable = true},
	{name = "Red Cabinet Set Piece", model = 2129, price = 375, offset = 0, isRenderable = true},
	{name = "Red Cabinet Set Piece", model = 2304, price = 375, offset = 0, isRenderable = true},
	{name = "White Cabinet Set Piece", model = 2131, price = 375, offset = 0, isRenderable = true},
	{name = "White Cabinet Set Piece", model = 2132, price = 375, offset = 0, isRenderable = true},
	{name = "White Cabinet Set Piece", model = 2133, price = 375, offset = 0, isRenderable = true},
	{name = "White Cabinet Set Piece", model = 2134, price = 375, offset = 0, isRenderable = true},
	{name = "White Cabinet Set Piece", model = 2141, price = 375, offset = 0, isRenderable = true},
	{name = "Brown Cabinet Set Piece", model = 2135, price = 375, offset = 0, isRenderable = true},
	{name = "Brown Cabinet Set Piece", model = 2136, price = 375, offset = 0, isRenderable = true},
	{name = "Brown Cabinet Set Piece", model = 2137, price = 375, offset = 0, isRenderable = true},
	{name = "Brown Cabinet Set Piece", model = 2138, price = 375, offset = 0, isRenderable = true},
	{name = "Brown Cabinet Set Piece", model = 2139, price = 375, offset = 0, isRenderable = true},
	{name = "Brown Cabinet Set Piece", model = 2140, price = 375, offset = 0, isRenderable = true},
	{name = "Kitchen Set", model = 15036, price = 1250, offset = 0, isRenderable = true},
	{name = "Bar Set", model = 16151, price = 1350, offset = 0, isRenderable = true},
	},
{
		name = "Bathroom/Toilet Equipment",
	{name = "Bathroom Furniture Piece", model = 2516, price = 175, offset = 0, isRenderable = true},
	{name = "Bathroom Furniture Piece", model = 2517, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2518, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2519, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2520, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2521, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2522, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2523, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2524, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2525, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2526, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bathroom Furniture Piece", model = 2527, price = 175, offset = 0, isRenderable = true}, 
	},
{
		name = "Sporting Goods",
	{name = "Treadmill", model = 2627, price = 375, offset = 0, isRenderable = true},
	{name = "Weightlifting Machine", model = 2629, price = 300, offset = 0, isRenderable = true}, 
	{name = "Sporting Goods", model = 2628, price = 175, offset = 0, isRenderable = true}, 
	{name = "Bicycle", model = 2630, price = 200, offset = 0, isRenderable = true}, 
	{name = "Punching Bag", model = 1985, price = 150, offset = 0, isRenderable = true}, 
	},
}

radio_channels = {
	--[1] = {"name", "link"},
		[1]={"Power Hit Raadio", "http://stream.power.ee/PHR.m3u"},
		[2]={"MyDonese", "http://provisioning.streamtheworld.com/pls/RADIO_MYDONOSEAAC.pls"},
	    [3]={"RauteMusik", "http://bcb-high.rautemusik.fm"},
	    [4]={"Radio Metal", "http://192.99.62.212:9854/listen.pls?sid=1&t=.m3u"},
	    [5]={"Hip-Hop", "http://149.56.175.167:5461/listen.pls?sid=1&t=.m3u"},
	    [6]={"Star FM Raadio", "http://stream.power.ee/StarFM.m3u"},
	    [7]={"Slager FM", "http://92.61.114.159:7812/slagerfm256.mp3"},
	    [8]={"Fm Jamaica Radio", "http://us2.internet-radio.com:8487/listen.pls&t=.m3u"},
	    [9]={"Rude Boy Radio", "http://64.71.79.181:5049/listen.pls?sid=1&t=.m3u"},
	    [10]={"Country Radio", "http://uk6.internet-radio.com:8465/listen.pls&t=.m3u"},
	    [11]={"Underground FM", "http://broadcast.infomaniak.net/generationfm-underground-high.mp3.m3u"},
	    [12]={"Old School Rap", "http://relay.181.fm:8068/"},
	    [13]={"PARTY VIBE RADIO", "http://www.partyviberadio.com:8020/listen.pls?sid=2&t=.m3u"},
	    [14]={"FMHiphop", "http://149.56.175.167:5708/listen.pls?sid=1&t=.m3u"},
	    [15]={"Black Beats FM", "http://stream3.blackbeats.fm/"},
	    [16]={"Radio Miami", "http://uk5.internet-radio.com:8251/listen.pls&t=.m3u"},
	    [17]={"EYE of DESTINY Radio", "http://uk6.internet-radio.com:8428/listen.pls&t=.m3u"},
	    [18]={"Radio Panther", "http://de1.internet-radio.com:8049/listen.pls&t=.m3u"},
	    [19]={"Metro FM", "http://provisioning.streamtheworld.com/pls/METRO_FMAAC.pls"},
	    [20]={"RADYOLAND - CLASSICLAND", "http://46.20.3.246/stream/59/"},
	    [21]={"RADYOLAND - ROCKLAND", "http://46.20.3.246/stream/57/"},
	    [22]={"M2 ROCK", "http://live.m2stream.fr/m2rock-128.mp3"},
	    [23]={"M2 Hip Hop", "http://live.m2stream.fr/m2hip-hop-128.mp3"},
	    [24]={"RADYONOM", "http://radyo.dogannet.tv/dfloor"},
	    [25]={"Virgin Rock", "http://vr-wr5-mp3-128.scdn.arkena.com/virginradio.mp3"},
	    [26]={"SKYFALL", "http://8.38.78.173:8093/listen.pls?sid=1&t=.pls"},
}

textures = {
	["walltexs"] = {
		{"newtexture/wall/paint/1.png",price = 50},
		{"newtexture/wall/paint/2.png",price = 50},
		{"newtexture/wall/paint/3.png",price = 50},
		{"newtexture/wall/paint/4.png",price = 50},
		{"newtexture/wall/paint/5.png",price = 50},
		{"newtexture/wall/paint/6.png",price = 50},
		{"newtexture/wall/paint/7.png",price = 50},
		{"newtexture/wall/paint/8.png",price = 50},
		{"newtexture/wall/paint/9.png",price = 50},
		{"newtexture/wall/paint/10.png",price = 50},
		{"newtexture/wall/paint/11.png",price = 50},
		{"newtexture/wall/paint/12.png",price = 50},
		{"newtexture/wall/paint/13.png",price = 50},
		{"newtexture/wall/paint/14.png",price = 50},
		{"newtexture/wall/paint/15.png",price = 50},
		{"newtexture/wall/paint/16.png",price = 50},
		{"newtexture/wall/paint/17.png",price = 50},
		{"newtexture/wall/paint/18.png",price = 50},
		{"newtexture/wall/paint/19.png",price = 50},
		{"newtexture/wall/paint/20.png",price = 50},
		{"newtexture/wall/paint/21.png",price = 50},
		{"newtexture/wall/tile/1.png",price = 50},
		{"newtexture/wall/tile/2.png",price = 50},
		{"newtexture/wall/tile/3.png",price = 50},
		{"newtexture/wall/tile/4.png",price = 50},
		{"newtexture/wall/tile/5.png",price = 50},
		{"newtexture/wall/tile/6.png",price = 50},
		{"newtexture/wall/tile/7.png",price = 50},
		{"newtexture/wall/tile/8.png",price = 50},
		{"newtexture/wall/tile/9.png",price = 50},
		{"newtexture/wall/tile/10.png",price = 50},
		{"newtexture/wall/tile/11.png",price = 50},
		{"newtexture/wall/tile/12.png",price = 50},
		{"newtexture/wall/tile/13.png",price = 50},
		{"newtexture/wall/tile/14.png",price = 50},
		{"newtexture/wall/tile/15.png",price = 50},
		{"newtexture/wall/tile/16.png",price = 50},
		{"newtexture/wall/tile/17.png",price = 50},
		{"newtexture/wall/tile/18.png",price = 50},
		{"newtexture/wall/tile/19.png",price = 50},
		{"newtexture/wall/tile/20.png",price = 50},

		{"newtexture/wall/wallpaper/1.png",price = 50},
		{"newtexture/wall/wallpaper/2.png",price = 50},
		{"newtexture/wall/wallpaper/3.png",price = 50},
		{"newtexture/wall/wallpaper/4.png",price = 50},
		{"newtexture/wall/wallpaper/5.png",price = 50},
		{"newtexture/wall/wallpaper/6.png",price = 50},
		{"newtexture/wall/wallpaper/7.png",price = 50},
		{"newtexture/wall/wallpaper/8.png",price = 50},
		{"newtexture/wall/wallpaper/9.png",price = 50},
		{"newtexture/wall/wallpaper/10.png",price = 50},
		{"newtexture/wall/wallpaper/11.png",price = 50},
		{"newtexture/wall/wallpaper/12.png",price = 50},
		{"newtexture/wall/wallpaper/13.png",price = 50},
		{"newtexture/wall/wallpaper/14.png",price = 50},
		{"newtexture/wall/wallpaper/15.png",price = 50},
		{"newtexture/wall/wallpaper/16.png",price = 50},
		{"newtexture/wall/wallpaper/17.png",price = 50},
		{"newtexture/wall/wallpaper/18.png",price = 50},
		{"newtexture/wall/wallpaper/19.png",price = 50},
		{"newtexture/wall/wallpaper/20.png",price = 50},
		{"newtexture/wall/wallpaper/21.png",price = 50},
	},
	["floortexs"] = {
		{"newtexture/wall/carpet/1.png",price = 75},
		{"newtexture/wall/carpet/2.png",price = 75},
		{"newtexture/wall/carpet/3.png",price = 75},
		{"newtexture/wall/carpet/4.png",price = 75},
		{"newtexture/wall/carpet/5.png",price = 75},
		{"newtexture/wall/carpet/6.png",price = 75},
		{"newtexture/wall/carpet/7.png",price = 75},
		{"newtexture/wall/carpet/8.png",price = 75},
		{"newtexture/wall/carpet/9.png",price = 75},
		{"newtexture/wall/carpet/10.png",price = 75},
		{"newtexture/wall/carpet/11.png",price = 75},
		{"newtexture/wall/carpet/12.png",price = 75},
		{"newtexture/wall/carpet/13.png",price = 75},
		{"newtexture/wall/carpet/14.png",price = 75},
		{"newtexture/wall/carpet/15.png",price = 75},
		{"newtexture/wall/carpet/16.png",price = 75},
		{"newtexture/wall/carpet/17.png",price = 75},
		{"newtexture/wall/carpet/18.png",price = 75},
		{"newtexture/wall/carpet/19.png",price = 75},
		{"newtexture/wall/carpet/20.png",price = 75},
		{"newtexture/wall/carpet/21.png",price = 75},
		{"newtexture/wall/wood/1.png",price = 100},
		{"newtexture/wall/wood/2.png",price = 100},
		{"newtexture/wall/wood/3.png",price = 100},
		{"newtexture/wall/wood/4.png",price = 100},
		{"newtexture/wall/wood/5.png",price = 100},
		{"newtexture/wall/wood/6.png",price = 100},
		{"newtexture/wall/wood/7.png",price = 100},
		{"newtexture/wall/wood/8.png",price = 100},
		{"newtexture/wall/wood/9.png",price = 100},
		{"newtexture/wall/wood/10.png",price = 100},
		{"newtexture/wall/wood/11.png",price = 100},
		{"newtexture/wall/wood/12.png",price = 100},
		{"newtexture/wall/wood/13.png",price = 100},
		{"newtexture/wall/wood/14.png",price = 100},
		{"newtexture/wall/wood/15.png",price = 100},
		{"newtexture/wall/wood/16.png",price = 100},
		{"newtexture/wall/wood/17.png",price = 100},
		{"newtexture/wall/wood/18.png",price = 100},
		{"newtexture/wall/wood/19.png",price = 100},
		{"newtexture/wall/wood/20.png",price = 100},
		{"newtexture/wall/wood/21.png",price = 100},
		{"newtexture/wall/wood/22.png",price = 100},
		{"newtexture/wall/wood/23.png",price = 100},
		{"newtexture/wall/wood/24.png",price = 100},
		{"newtexture/wall/wood/25.png",price = 100},
		{"newtexture/wall/wood/26.png",price = 100},
		{"newtexture/wall/wood/27.png",price = 100},
		{"newtexture/wall/wood/28.png",price = 100},
		{"newtexture/wall/wood/29.png",price = 100},
		{"newtexture/wall/wood/30.png",price = 100},
		{"newtexture/wall/wood/31.png",price = 100},
		{"newtexture/wall/wood/32.png",price = 100},
	},
	["doortexs"] = {
		{"newtexture/door/1.png",price = 25},
		{"newtexture/door/2.png",price = 25},
		{"newtexture/door/3.png",price = 25},
		{"newtexture/door/4.png",price = 25},
		{"newtexture/door/5.png",price = 25},
		{"newtexture/door/6.png",price = 25},
		{"newtexture/door/7.png",price = 25},
		{"newtexture/door/8.png",price = 25},
		{"newtexture/door/9.png",price = 25},
		{"newtexture/door/10.png",price = 25},
		{"newtexture/door/11.png",price = 25},
		{"newtexture/door/12.png",price = 25},
		{"newtexture/door/13.png",price = 25},
		{"newtexture/door/14.png",price = 25},
		{"newtexture/door/15.png",price = 25},
		{"newtexture/door/16.png",price = 25},
		{"newtexture/door/17.png",price = 25},
		{"newtexture/door/18.png",price = 25},
		{"newtexture/door/19.png",price = 25},
		{"newtexture/door/20.png",price = 25},
		{"newtexture/door/21.png",price = 25},
		{"newtexture/door/22.png",price = 25},
	},
}

color = {
	["hex"] = "#54a0ff",
	["rgb"] = {84, 160, 255},
}